# Customer base configuration template
customer:
  name: "CUSTOMER_NAME_HERE"
  prefix: "PREFIX_HERE"

architecture:
  medallion:
    bronze_layer: true
    silver_layer: true
    gold_layer: true

capacity:
  fabric_capacity_id: "FABRIC_CAPACITY_ID_HERE"

advanced:
  custom_tags:
    customer: "CUSTOMER_TAG_HERE"
    project: "PROJECT_NAME_HERE"