# Customer base configuration template
customer:
  name: "BetaTestName"
  prefix: "beta-test-prefix"

architecture:
  medallion:
    bronze_layer: true
    silver_layer: true
    gold_layer: true

capacity:
  fabric_capacity_id: "E075F770-5EAD-4BA7-B04B-E889209A4055"

advanced:
  custom_tags:
    customer: "beta-test-tag"
    project: "data-platform"