# Development environment overrides
workspace_id: "DEV_WORKSPACE_GUID_HERE"
capacity_settings:
  compute_scale: "small"
  auto_scale: false
environment_tags:
  environment: "development"
debug_mode: true